# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CachegrandServerlessCli < Formula
  desc "cachegrand serverless cli"
  homepage "https://github.com/cachegrand/cachegrand-serverless-cli"
  version "1.0.0-alpha10"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cachegrand/cachegrand-serverless-cli/releases/download/v1.0.0-alpha10/cachegrand-serverless-cli_1.0.0-alpha10_macOS_x86_64.zip"
      sha256 "db0d8365256797efbf5d0b2cff5dc55da8211599b56da70c569f5a383e5b18aa"

      def install
        bin.install "cg-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cachegrand/cachegrand-serverless-cli/releases/download/v1.0.0-alpha10/cachegrand-serverless-cli_1.0.0-alpha10_macOS_arm64.zip"
      sha256 "18c99d1dd11e8a1ebb57423c620aab42dabe6a2eeb75ead8785af257ead41cd3"

      def install
        bin.install "cg-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/cachegrand/cachegrand-serverless-cli/releases/download/v1.0.0-alpha10/cachegrand-serverless-cli_1.0.0-alpha10_linux_armv6.tar.gz"
      sha256 "3dd98f47da84f519fc5b2a462bafb6ea6ee39855bbfff8d760c6b1642e1dcf10"

      def install
        bin.install "cg-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cachegrand/cachegrand-serverless-cli/releases/download/v1.0.0-alpha10/cachegrand-serverless-cli_1.0.0-alpha10_linux_x86_64.tar.gz"
      sha256 "451b3430b0ecfa94f48196c597ff76f340cb62d9dd20b4df0a619485a0da6992"

      def install
        bin.install "cg-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cachegrand/cachegrand-serverless-cli/releases/download/v1.0.0-alpha10/cachegrand-serverless-cli_1.0.0-alpha10_linux_arm64.tar.gz"
      sha256 "340cd45d172a1d85c38df57938da5d35304d4907cafd033aefb2d83e8c2e407d"

      def install
        bin.install "cg-cli"
      end
    end
  end
end
