# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CachegrandServerlessCli < Formula
  desc "cachegrand serverless cli"
  homepage "https://github.com/cachegrand/cachegrand-serverless-cli"
  version "1.0.0-alpha.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cachegrand/cachegrand-serverless-cli/releases/download/v1.0.0-alpha.9/cachegrand-serverless-cli_1.0.0-alpha.9_macOS_x86_64.zip"
      sha256 "790ab254c33b890df1d3d4544ca7878185a335d1639c13a68b47e0142f8c50eb"

      def install
        bin.install "cg-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cachegrand/cachegrand-serverless-cli/releases/download/v1.0.0-alpha.9/cachegrand-serverless-cli_1.0.0-alpha.9_macOS_arm64.zip"
      sha256 "34159bd59021b5bfa56c2909902e02af8e2caec84f5f99d1e5fe873cf08e115b"

      def install
        bin.install "cg-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/cachegrand/cachegrand-serverless-cli/releases/download/v1.0.0-alpha.9/cachegrand-serverless-cli_1.0.0-alpha.9_linux_armv6.tar.gz"
      sha256 "533a60bfa9116784fc0853ea7f0ab7f36aa958f587383888352d6322625fecd4"

      def install
        bin.install "cg-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cachegrand/cachegrand-serverless-cli/releases/download/v1.0.0-alpha.9/cachegrand-serverless-cli_1.0.0-alpha.9_linux_x86_64.tar.gz"
      sha256 "68b6c7d77d3694e780c04ef9d5ee6473f49e03d6baeabf6546ebf018e75b8679"

      def install
        bin.install "cg-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cachegrand/cachegrand-serverless-cli/releases/download/v1.0.0-alpha.9/cachegrand-serverless-cli_1.0.0-alpha.9_linux_arm64.tar.gz"
      sha256 "d2c4934476335af0e7cdbe91e2221a6f17e9a0404bf7b9474ef0a2af7956a883"

      def install
        bin.install "cg-cli"
      end
    end
  end
end
