# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CachegrandServerlessCli < Formula
  desc "cachegrand serverless cli"
  homepage "https://github.com/cachegrand/cachegrand-serverless-cli"
  version "1.0.0-rc.2"
  license "GPL3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cachegrand/cachegrand-serverless-cli/releases/download/v1.0.0-rc.2/cachegrand-serverless-cli_1.0.0-rc.2_macOS_arm64.zip"
      sha256 "cd94ac36b3a8f0057964c7d9b08c3bdf090ab721e6d0ee00e77869eec6250f1a"

      def install
        bin.install "cg-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cachegrand/cachegrand-serverless-cli/releases/download/v1.0.0-rc.2/cachegrand-serverless-cli_1.0.0-rc.2_macOS_amd64.zip"
      sha256 "566d66cdb24857620e2981e31d8b2fd7648c110c7b56e66c9fb2e0b76d80be98"

      def install
        bin.install "cg-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cachegrand/cachegrand-serverless-cli/releases/download/v1.0.0-rc.2/cachegrand-serverless-cli_1.0.0-rc.2_linux_arm64.tar.gz"
      sha256 "0e73493108ea86ff0af1743a6a84e00c1cf331b2731a96f45e54588bd1096ec3"

      def install
        bin.install "cg-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cachegrand/cachegrand-serverless-cli/releases/download/v1.0.0-rc.2/cachegrand-serverless-cli_1.0.0-rc.2_linux_amd64.tar.gz"
      sha256 "3d5f85db9c7cb02159b8fa6014f407415efa4d77bfaac00a4bdb2a9b6c348958"

      def install
        bin.install "cg-cli"
      end
    end
  end
end
